AllCops:
  TargetRubyVersion: 2.5.3
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'node_modules/**/*'
    - 'script/**/*'
    - 'support/**/*'
    - 'tmp/**/*'
    - 'test/**/*'

ConditionalAssignment:
  Enabled: false
StringLiterals:
  Enabled: false
RedundantReturn:
  Enabled: false
Documentation:
  Enabled: false
WordArray:
  Enabled: false
AbcSize:
  Enabled: false
MutableConstant:
  Enabled: false
SignalException:
  Enabled: false
Casecmp:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
MissingRespondToMissing:
  Enabled: false
MethodMissingSuper:
  Enabled: false
MethodLength:
  Max: 20
Style/FrozenStringLiteralComment:
  Enabled: false
LineLength:
  Max: 120
Style/EmptyMethod:
  Enabled: false
Style/UnneededInterpolation:
  Enabled: false
Bundler/OrderedGems:
  Enabled: false
